#!/usr/bin/env python3
"""Regenerate design-system/tokens.css from index.html.

The design system must never drift from the app, so tokens.css is never
hand-edited: every value in it is extracted from the single <style> block
in ../index.html. Run this after any change to the app's :root block:

    python design-system/_build.py

Prints the version string it found in the drawer brand line.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT.parent / "index.html"
OUT = ROOT / "tokens.css"

KEEP = (":root", "[data-mode", "html", "body")


def main():
    src = SRC.read_text(encoding="utf-8")
    m = re.search(r"<style[^>]*>(.*?)</style>", src, re.S)
    if not m:
        sys.exit("no <style> block found in index.html")
    css = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)

    rules = []
    for sel, body in re.findall(r"([^{}]+)\{([^{}]*)\}", css):
        sel = " ".join(sel.split())
        if not sel.startswith(KEEP):
            continue
        decls = [d.strip() for d in body.split(";") if d.strip().startswith("--")]
        if decls:
            rules.append((sel, decls))

    font = re.search(r"\bbody\s*\{[^{}]*?font-family\s*:\s*([^;}]+)", css, re.S)
    font = " ".join(font.group(1).split()) if font else "unknown"
    ver = re.search(r'class="brand"[^>]*>\s*Kubik\s*<span[^>]*>([^<]+)</span>', src)
    ver = ver.group(1).strip() if ver else "unknown"

    out = [
        "/* GENERATED by design-system/_build.py - do not edit by hand.",
        "   Extracted verbatim from index.html (Kubik %s)." % ver,
        "   Body font stack: %s */" % font,
        "",
    ]
    for sel, decls in rules:
        out.append(sel + " {")
        out += ["  " + d + ";" for d in decls]
        out.append("}")
        out.append("")
    OUT.write_text("\n".join(out), encoding="utf-8")
    print("wrote %s - %d rule(s), Kubik %s" % (OUT.name, len(rules), ver))


if __name__ == "__main__":
    main()
